{% set name = "pycrostates" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycrostates-{{ version }}.tar.gz
  sha256: 47d57dcea7f431b12d046a31dbe4457f8540cbcf8c98da45dd25c2dd2046afd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - pycrostates-sys_info = pycrostates.commands.sys_info:run

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64.0.0
  run:
    - decorator
    - jinja2
    - joblib
    - matplotlib-base >=3.5
    - mne-base >=1.2
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - python >=3.9
    - scikit-learn
    - scipy

test:
  imports:
    - pycrostates
  commands:
    - pip check
    - pycrostates-sys_info
  requires:
    - pip

about:
  home: https://pycrostates.readthedocs.io/en/latest/
  summary: A simple open source Python package for EEG microstate segmentation.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/vferat/pycrostates

extra:
  recipe-maintainers:
    - vferat
    - mscheltienne
