{% set name = "pycrostates" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycrostates-{{ version }}.tar.gz
  sha256: c7247b0968c289461a7d9a3ccae09d2c917692c01b3052ba014a95f763527075

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=61.0.0
    - wheel
  run:
    - decorator
    - importlib-metadata
    - importlib-resources
    - jinja2
    - joblib
    - matplotlib-base
    - mne-base >=1.0
    - numpy >=1.20.0
    - pooch
    - python >=3.7
    - scikit-learn
    - scipy

test:
  imports:
    - pycrostates
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pycrostates.readthedocs.io/en/latest/
  summary: A simple open source Python package for EEG microstate segmentation.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/vferat/pycrostates

extra:
  recipe-maintainers:
    - vferat
    - mscheltienne
