{% set name = "pycrostates" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycrostates-{{ version }}.tar.gz
  sha256: 62cccd98f43ed4ebf8d4a38f55f20c389b309c7f4637a1ef2d28543338aa5150

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - pycrostates-sys_info = pycrostates.commands.sys_info:run

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64.0.0
  run:
    - decorator
    - jinja2
    - joblib
    - matplotlib-base >=3.5
    - mne-base >=1.2
    - numpy >=1.21
    - packaging
    - pooch
    - psutil
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - pycrostates
  commands:
    - pip check
    - pycrostates-sys_info
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pycrostates.readthedocs.io/en/latest/
  summary: A simple open source Python package for EEG microstate segmentation.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/vferat/pycrostates

extra:
  recipe-maintainers:
    - vferat
    - mscheltienne
